general.live_config_reload = true

[terminal.shell]
#program="c:/software/Git/bin/bash.exe"
program = "c:/software/Git/usr/bin/zsh.exe"
args = ["--login", "-i"]

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "#00D1FF"

[env]
TERM = "xterm-256color"

[colors.search.focused_match]
background = "#00D1FF"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[cursor.style]
shape = "Beam"
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
[font]
size = 17.0

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\f"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
opacity = 1
[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 2
y = 2
